import { Atom, BadgeCheck, Blocks, Boxes, BrainCircuit, Braces, Code2, Component, Container, Database, FileCode2, Files, FlaskConical, FormInput, Gauge, GitBranch, GitMerge, Globe2, Hammer, HardDrive, Image as ImageIcon, Kanban, KeyRound, Layers3, LockKeyhole, Map, MonitorCog, Network, Package, Palette, PanelsTopLeft, PenTool, Plug, Printer, RefreshCw, Route, ScanSearch, Search, Server, ShieldCheck, Store, Table2, Triangle, WifiOff, Workflow, Wrench } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const skillIcons: Record<string, LucideIcon> = {
  atom: Atom,
  'badge-check': BadgeCheck,
  blocks: Blocks,
  boxes: Boxes,
  brain: BrainCircuit,
  braces: Braces,
  code: Code2,
  component: Component,
  container: Container,
  database: Database,
  'file-code': FileCode2,
  files: Files,
  form: FormInput,
  gauge: Gauge,
  'git-branch': GitBranch,
  'git-merge': GitMerge,
  globe: Globe2,
  hammer: Hammer,
  'hard-drive': HardDrive,
  image: ImageIcon,
  kanban: Kanban,
  key: KeyRound,
  layers: Layers3,
  lock: LockKeyhole,
  map: Map,
  monitor: MonitorCog,
  network: Network,
  package: Package,
  palette: Palette,
  panels: PanelsTopLeft,
  'pen-tool': PenTool,
  plug: Plug,
  printer: Printer,
  refresh: RefreshCw,
  route: Route,
  scan: ScanSearch,
  search: Search,
  server: Server,
  shield: ShieldCheck,
  store: Store,
  table: Table2,
  test: FlaskConical,
  triangle: Triangle,
  'wifi-off': WifiOff,
  workflow: Workflow,
  wrench: Wrench
}

export const skillIconFor = (iconName: string) => skillIcons[iconName] ?? Code2
