export const WorkFaceTokens = {
  eyebrow: { className: 'eyebrow mt-auto mb-2.5 flex justify-between gap-4 font-mono text-[clamp(.58rem,.76vw,.7rem)] uppercase text-white/70 max-[760px]:text-[.53rem]' },
  stack: { className: 'project-stack mt-4 grid gap-px bg-white/20' },
  row: { className: 'project-row grid w-full min-w-0 grid-cols-[1.8rem_minmax(0,1fr)_minmax(0,8.5rem)] items-baseline gap-2 bg-[rgba(8,10,9,.78)] px-1 py-3 text-left text-white max-[760px]:py-2 [&>span]:font-mono [&>span]:text-[.55rem] [&>span]:text-white/60 [&>small]:truncate [&>small]:font-mono [&>small]:text-[.55rem] [&>small]:text-white/60 max-[760px]:[&>small]:hidden [&>strong]:truncate [&>strong]:text-[clamp(.81rem,1.08vw,.98rem)]' },
  actions: { className: 'work-actions pointer-events-auto absolute inset-x-[var(--face-padding)] bottom-[var(--face-padding)] z-8 grid gap-px [transform:translateZ(var(--half-cube))]' },
  hiddenActions: { className: '!pointer-events-none !opacity-0' },
  action: { className: 'relative grid w-full min-w-0 grid-cols-[1.8rem_minmax(0,1fr)_minmax(0,8.5rem)] items-baseline gap-2 overflow-hidden bg-[rgba(8,10,9,.78)] px-1 py-3 text-left text-white transition-[transform,background] duration-300 hover:z-2 hover:[transform:translateX(.75rem)] hover:bg-[rgba(23,48,108,.96)] [[data-language=ar]_&]:text-right [[data-language=ar]_&]:hover:[transform:translateX(-.75rem)] max-[760px]:py-2 [&>span]:font-mono [&>span]:text-[.55rem] [&>span]:text-white/60 [&>small]:truncate [&>small]:font-mono [&>small]:text-[.55rem] [&>small]:text-white/60 max-[760px]:[&>small]:hidden [&>strong]:truncate [&>strong]:text-[clamp(.81rem,1.08vw,.98rem)]' },
  more: { className: 'absolute right-1.5 top-1/2 [[data-language=ar]_&]:left-1.5 [[data-language=ar]_&]:right-auto min-w-[5.5rem] translate-x-4 -translate-y-1/2 bg-accent px-2 py-1.5 font-mono text-[.47rem] font-medium opacity-0 shadow-[0_0_18px_rgba(49,92,255,.35)] transition-[opacity,transform] duration-[220ms] group-hover:translate-x-0 group-hover:opacity-100' }
}
